"""update discount model

Revision ID: 99e8b321e74b
Revises: a1c61a49562d
Create Date: 2021-07-12 03:39:27.974730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e8b321e74b'
down_revision = 'a1c61a49562d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'rate')
    # ### end Alembic commands ###
