"""Model discount

Revision ID: a1c61a49562d
Revises: 8da68f051def
Create Date: 2021-07-11 19:45:35.757854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c61a49562d'
down_revision = '8da68f051def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_campaign_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_campaign_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts')
    # ### end Alembic commands ###
